"""Prompt templates for all agents."""

from .templates import (
    TOPIC_PLANNER_PROMPT,
    INTERVIEWER_PROMPT,
    ANSWER_ANALYZER_PROMPT,
    FACT_CHECKER_PROMPT,
    EVALUATOR_PROMPT,
    QUESTION_HANDLER_PROMPT,
    HIRING_MANAGER_PROMPT,
)

__all__ = [
    "TOPIC_PLANNER_PROMPT",
    "INTERVIEWER_PROMPT",
    "ANSWER_ANALYZER_PROMPT",
    "FACT_CHECKER_PROMPT",
    "EVALUATOR_PROMPT",
    "QUESTION_HANDLER_PROMPT",
    "HIRING_MANAGER_PROMPT",
]
